version: '2'
services:
    mecanica-app:
        image: mecanica
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mecanica-postgresql:5432/mecanica
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mecanica-postgresql:
        extends:
            file: postgresql.yml
            service: mecanica-postgresql
