version: '2'
services:
    mecanica-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/mecanica/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=mecanica
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
